### ISSUE TITLE
Typeerror with Lint on Windows

### ISSUE THREAD

**Issue by SrTobi** [HelfenKannJeder/come2help-web#35]
Running `$(npm bin)/sass-lint -c css/.sass-lint.yml -v` on Windows gives:

```
C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:57
                  'line': node.content[i + 1].start.line,
                                             ^
TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at Object.module.exports.detect (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:43:11)
    at C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:90:9)
    at detectPattern (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\bin\sass-lint.js:15:18)
    at Object.<anonymous> (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\bin\sass-lint.js:77:3)
```

**Comment by jGleitz** [comment]
This is already reported on the sass-lint project: sasstools/sass-lint#389

Could you post a detailed error report (Including OS, versions and our [.sass-lint.yml](https://github.com/HelfenKannJeder/come2help-web/blob/master/css/.sass-lint.yml)) there?

**Comment by SrTobi** [comment]
posted the details and the fix
